// src/config/initial-config.ts

export const INITIAL_APP_CONFIG = {
  superAdminPolicy: {
    subjectType: 'role',
    subjectId: 'superadmin',
    action: 'manage',
    resource: 'all',
    condition: {},
    description: 'Superadmin toàn quyền',
  },
  defaultTags: [
    // Chính trị - Xã hội
    'Chính Trị',
    'Pháp Luật',
    'Quốc Hội',
    'Đại Biểu',
    'Bầu Cử',
    'Xã Hội',
    'Dân Sinh',
    'An Ninh',
    // Quốc tế
    'Mỹ',
    'Trung Quốc',
    'Nga',
    'Ukraine',
    'NATO',
    'ASEAN',
    'EU',
    'Israel',
    'Palestine',
    // Kinh tế
    'Kinh Tế Vĩ Mô',
    'Doanh Nghiệp',
    'Startup',
    'Thị Trường',
    'Chứng Khoán',
    'Bất Động Sản',
    'Lạm Phát',
    // Công nghệ
    'Công Nghệ',
    'AI',
    'ChatGPT',
    'Blockchain',
    'Robot',
    'Big Data',
    'IoT',
    'Apple',
    'iPhone',
    'iPad',
    'MacBook',
    'Samsung',
    'Xiaomi',
    'Huawei',
    'Facebook',
    'Meta',
    'Google',
    'YouTube',
    'TikTok',
    'Elon Musk',
    'Tesla',
    'SpaceX',
    // Thể thao
    'Thể Thao',
    'Bóng Đá',
    'Ngoại Hạng Anh',
    'Champions League',
    'World Cup',
    'SEA Games',
    'Manchester United',
    'Man City',
    'Chelsea',
    'Arsenal',
    'Liverpool',
    'Ronaldo',
    'Messi',
    'Mbappe',
    'Thể Thao Điện Tử',
    'Liên Quân',
    'Liên Minh Huyền Thoại',
    'Dota 2',
    'CSGO',
    // Giải trí
    'Giải Trí',
    'Âm Nhạc',
    'Điện Ảnh',
    'Phim Chiếu Rạp',
    'Netflix',
    'Kpop',
    'Blackpink',
    'BTS',
    'Người Nổi Tiếng',
    'Sao Việt',
    'Truyền Hình Thực Tế',
    'Showbiz',
    // Sức khỏe
    'Sức Khỏe',
    'Y Tế',
    'Dinh Dưỡng',
    'Bệnh Viện',
    'Dịch Bệnh',
    'Covid-19',
    'Sức Khỏe Tinh Thần',
    // Giáo dục
    'Giáo Dục',
    'Thi Đại Học',
    'Điểm Chuẩn',
    'Học Sinh',
    'Sinh Viên',
    'Đại Học Bách Khoa',
    'Du Học',
    // Du lịch
    'Du Lịch',
    'Review Điểm Đến',
    'Ẩm Thực',
    'Hạ Long',
    'Sa Pa',
    'Đà Nẵng',
    'Phú Quốc',
    'Paris',
    'Tokyo',
    // Khoa học
    'Khoa Học',
    'Vũ Trụ',
    'NASA',
    'Kính Viễn Vọng James Webb',
    'Phát Minh',
    'Y Học Hiện Đại',
    // Văn hóa
    'Văn Hóa',
    'Phong Tục Tập Quán',
    'Nghệ Thuật',
    'Tranh Đông Hồ',
    'Lễ Hội Truyền Thống',
    // Giao thông - Xe
    'Giao Thông',
    'Tắc Đường',
    'Tai Nạn',
    'Xe Cộ',
    'Ôtô',
    'Xe Máy',
    'VinFast',
    'Ô Tô Điện',
    'Đánh Giá Xe',
    // Địa phương
    'Đông Anh',
    'Hà Nội',
    'TP HCM',
    'Đà Nẵng',
    'Cần Thơ',
    'Hải Phòng',
    // Bổ trợ
    'Tin Nhanh',
    'Phân Tích',
    'Phóng Sự',
    'Video',
    'Trực Tiếp',
    'Breaking News',
  ],
  superAdminUser: {
    email: 'superadmin@hari.com',
    password: '123qwe', // Mật khẩu mặc định, sẽ được hash trong code
    name: 'Super Admin',
    role: 'superadmin',
    isActive: true,
    isVerified: true,
    status: 'active',
  },
  defaultCategories: [
    {
      name: 'Thời sự',
      description:
        'Tin tức nóng hổi về chính trị, pháp luật, xã hội và các vấn đề trong nước.',
      coverImage: 'https://example.com/images/news.jpg',
    },
    {
      name: 'Thế giới',
      description:
        'Cập nhật tin tức quốc tế, quan hệ quốc tế và các sự kiện toàn cầu.',
      coverImage: 'https://example.com/images/world.jpg',
    },
    {
      name: 'Kinh tế',
      description: 'Tin tức về kinh tế, tài chính, doanh nghiệp và thị trường.',
      coverImage: 'https://example.com/images/economy.jpg',
    },
    {
      name: 'Công nghệ',
      description:
        'Các tin tức về công nghệ, đổi mới sáng tạo và xu hướng kỹ thuật số.',
      coverImage: 'https://example.com/images/technology.jpg',
    },
    {
      name: 'Thể thao',
      description: 'Tin tức, sự kiện, phân tích và lịch thi đấu thể thao.',
      coverImage: 'https://example.com/images/sports.jpg',
    },
    {
      name: 'Giải trí',
      description:
        'Tin tức về âm nhạc, điện ảnh, người nổi tiếng và văn hóa đại chúng.',
      coverImage: 'https://example.com/images/entertainment.jpg',
    },
    {
      name: 'Sức khỏe',
      description:
        'Thông tin về y tế, dinh dưỡng, lối sống và sức khỏe tinh thần.',
      coverImage: 'https://example.com/images/health.jpg',
    },
    {
      name: 'Giáo dục',
      description:
        'Tin tức và thông tin về giáo dục, học tập và phát triển kỹ năng.',
      coverImage: 'https://example.com/images/education.jpg',
    },
    {
      name: 'Du lịch',
      description:
        'Tin tức, điểm đến và kinh nghiệm du lịch trong nước và quốc tế.',
      coverImage: 'https://example.com/images/travel.jpg',
    },
    {
      name: 'Khoa học',
      description:
        'Khám phá về vũ trụ, khoa học tự nhiên và các phát minh mới.',
      coverImage: 'https://example.com/images/science.jpg',
    },
    {
      name: 'Văn hóa',
      description:
        'Thông tin về di sản, nghệ thuật, phong tục và giao lưu văn hóa.',
      coverImage: 'https://example.com/images/culture.jpg',
    },
    {
      name: 'Giao thông',
      description: 'Tin tức và chính sách về giao thông, quy hoạch hạ tầng.',
      coverImage: 'https://example.com/images/transportation.jpg',
    },
    {
      name: 'Xe',
      description: 'Tin tức, đánh giá và công nghệ liên quan đến xe cộ.',
      coverImage: 'https://example.com/images/vehicles.jpg',
    },
  ],
};
