export enum PrivacyType {
  PUBLIC = 'public',
  PRIVATE = 'private',
  FRIEND = 'friend',
}
export enum SocialPlatform {
  FACEBOOK = 'facebook',
  INSTAGRAM = 'instagram',
  X = 'x',
  TIKTOK = 'tiktok',
  YOUTUBE = 'youtube',
  LINKEDIN = 'linkedin',
  PINTEREST = 'pinterest',
  SNAPCHAT = 'snapchat',
  REDDIT = 'reddit',
  TUMBLR = 'tumblr',
  TWITCH = 'twitch',
  DISCORD = 'discord',
  GITHUB = 'github',
  GITLAB = 'gitlab',
  STACK_OVERFLOW = 'stackoverflow',
  MEDIUM = 'medium',
  SUBSTACK = 'substack',
  MASTODON = 'mastodon',
  BLUESKY = 'bluesky',
  FOURSQUARE = 'foursquare',
  VIMEO = 'vimeo',
  FLICKR = 'flickr',
  BEHANCE = 'behance',
  DRIBBBLE = 'dribbble',
  SOUNDCLOUD = 'soundcloud',
  SPOTIFY = 'spotify',
  APPLE_MUSIC = 'appleMusic',
  DEVIANTART = 'deviantart',
  ARTSTATION = 'artstation',
  KICK = 'kick',
  WECHAT = 'wechat',
  WHATSAPP = 'whatsapp',
  TELEGRAM = 'telegram',
  LINE = 'line',
  SKYPE = 'skype',
  QUORA = 'quora',
  GOODREADS = 'goodreads',
  ETSY = 'etsy',
  SHOPIFY = 'shopify',
  PATREON = 'patreon',
  KO_FI = 'koFi',
  BUY_ME_A_COFFEE = 'buymeacoffee',
  CASH_APP = 'cashApp',
  VENMO = 'venmo',
  PAYPAL = 'paypal',
  ONLYFANS = 'onlyfans',
  FANSLY = 'fansly',

  // Các liên kết chung/cá nhân
  WEBSITE = 'website',
  PORTFOLIO = 'portfolio',
  BLOG = 'blog',
}
